name: Verify Files

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  verify:
    runs-on: ubuntu-latest
    if: github.actor != 'pryge'
    steps:
      - name: verify-version
        uses: actions-cool/verify-files-modify@v1.1.0
        with:
          allowed-files: 'quotes.md'
          assignees: 'pryge'
          skip-verify-authority: 'write'
          comment: |
            Hi @${{ github.event.pull_request.user.login }}. Thanks for your contribution!  
            This repository only supports modifying `quotes.md`. I will review your PR later.
          close: true